### PR TITLE
New UI

### PR DESCRIPTION
**Pull request by bentranter**
Here it is - my huge PR. This PR makes the following changes:

- New mobile-first layout
- Adds a new label for full-year courses
- Enables click-to-copy for course synonyms

You can see screenshots of the new UI at [bentranter/thundr-minimal](https://github.com/bentranter/thundr-minimal).

The CSS and HTML were reworked to make the templates smaller (where it was possible). I used the OOCSS approach that has kind of started to catch on, which has helped me reduce nesting in any HTML templates I work with by quite a bit. The CSS is down to 1309 SLOC, and all the inline styles were removed from the HTML. I'm also 90% sure the jQuery dependency can be removed, but that's not included in this PR. I also refactored the pagination function and moved its script from above the tmeplate to below the template.

This is tested with my fork of Thundr so its probably ok to merge as-is, but I'd like to add some type of UI notification to the user when they click-to-copy a synonym (to let them know it worked), and to remove the jQuery dependency (and be 100% confident about doing so haha)

*Edit*: I also added pretty detailed installation and development instructions to the README to encourage more people to contribute, as well as a small blurb about contributing. I can change that as needed, but I think it'd be cool if more Lakehead students were interested in contributing to this :)

### CODE REVIEW

**Comment by bentranter** [comment]
This now enables CORS on every requested resource.

**Comment by flyingtoaster0** [comment]
Checked out the branch, spun up my local server, went off without a hitch!

**Comment by bentranter** [comment]
Awesome!

**Comment by flyingtoaster0** [comment]
also, lmao @ 43cddc914204842b79dc60bf28f0b8fb0ddad5c0

**Pull request merged**
